---
OrdererOrgs:
  - Name: orderer
    Domain: orderer
    Specs:
      - Hostname: orderer1
        SANS:
          - 192.168.1.5

PeerOrgs:
  - Name: cbfc.movie.com
    Domain: cbfc.movie.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.cbfc.movie.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer0
        CommonName: peer0.cbfc.movie.com
        SANS:
          - 192.168.1.5
  - Name: inox.movie.com
    Domain: inox.movie.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.inox.movie.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer0
        CommonName: peer0.inox.movie.com
        SANS:
          - 192.168.1.5
  - Name: pvr.movie.com
    Domain: pvr.movie.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.pvr.movie.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer0
        CommonName: peer0.pvr.movie.com
        SANS:
          - 192.168.1.5
  - Name: tokenplatform.movie.com
    Domain: tokenplatform.movie.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.tokenplatform.movie.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer0
        CommonName: peer0.tokenplatform.movie.com
        SANS:
          - 192.168.1.5
